language: python
matrix:
  include:
  - python: 2.7
    env:
    - secure: pPI0jr6n0v8hpQezrEPJ0xWchiTw5br+W/gSAte+NAhzR0wkc01RDDcQ0uMuq6ypVA/dLTGVPg9cb4f2x54iGoU1QNGTg2ppv2I1WGXovQXMgHYO29ucKG3MF1HG+7kVk86QZlohLR3TTguwzWyoV/0506Bw7bVsOVA7H1lyBX2/6LR9lXIHHv7cRNhsS3DiKxF3JLChUi4DWJgJ/mfHqI8oYQJ8Qg7XBHH8prJOHVvdOqHqjgM/s9KTLnT2U5K4F6D2ao+iPlnkdzqMsgFxJ2LgGWmXyrvD5PJg1h220BV56HbOsrLHQeGlLiTs399LL7rbJAjRz00tMUa9yWa/CLpzzfX3ejww5vZDC5nudivX4s+AXN1JKdMlFVJG84gVIsvQyxyxbL1lhD56rNS/jci3Tlof0iWVkq2GGN+g8Dp6MsCkZgdzGF6Tyl8pP3pZkjVXK2RBNMr+/x6hcCdZyAqmEkdPvcGL2l7X9VyeqAJltoMIPOrrm0oaChy0TS/RIY3lwI7a7I45J6ntEWs3kcbm1t3ktsczd7PUtKWhXCoaAtrnPQMFqPgBFd+9q/wHweDUtKDBwxwEdZ3dlde4nXIP42AnP7kKXPbAp0rR/TipMcohNKPRVshAbHCYVTVZDk7DLbahvDJ6V8t6yqxeBYbkMKHUON8qK4r6Tf34DvU=
    - secure: eBUctmFI315PioLahtiiSk4Wn2VF8TzkoWk7zArL25VoNeUCLSsW2/5PAv99ZJXJmxVpURj2vm+qigCerGS2T7cY8hRWnQQpAsGppsMf9oHPUuAefyx6TOaKa4UUTpWQkcmU8refFp0Db5DuzyLGUMaX5inEgMsbbs+d4/2IZTEmLmmKW8750aD5T5nIkhoNS5X1KJD9ne+t2IaIsON5/8pH/vgsiMkT9RlhHe2ZfvEqoO5ntu0CvGbmtWkSzB+SfMMlGjlnln9aAYtqShVhaQeMUnxbAUiz6u2kEE9z4gvXVd0H86HEOR7vBrRHJiFzXJ4Bhu8pX6KbKx76rsljwUFAVJj68e/v/m6UpFfsR+6G8lEanvnVwDdhfrzKGRpKjVYoEH9QsRAz7gHQt+zeqNKjZ3e4r/1RjdJqWky8cUpPVtxUexsfW4hSpvG1b3Xqt5ADP1Vyy1SLJ6/WFoN2+xtwp22ufr919M7lcdumF2VYo74eeH4r8Ri2gTRHmRpMnhZWYGDUT6s774qni6VUYwDYHQ9cuYwbnucU7ZZNdGCL7Z9LKcXrz4pgYeQAnrQAdnbxCgTuxA1EJnxaga9lhZb8DLnqzIXU4e6lFugDEdJUICZwLhrrM1nNr2N7/S/wX1MsEx13NKTEUIgtnnze2J2OxyfW8mh3QhKUHyBOf1k=
    - BOB_DOCUMENTATION_SERVER=https://www.idiap.ch/software/bob/docs/latest/bioidiap/%s/master
    - BOB_UPLOAD_WHEEL="--universal"
  - python: 3.3
  - python: 3.4
  - python: 3.5
before_install:
# - sudo add-apt-repository -y ppa:biometrics/bob
- sudo apt-get update -qq
- sudo apt-get install -qq --force-yes dvipng texlive-latex-base texlive-latex-extra texlive-math-extra texlive-latex-recommended texlive-fonts-recommended
- pip install --upgrade pip
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel sphinx nose numpy scipy matplotlib coverage
- pip install --find-links https://www.idiap.ch/software/bob/wheels/travis/ --use-wheel --pre -r requirements.txt coveralls
install:
- python bootstrap-buildout.py
- ./bin/buildout buildout:develop=. buildout:extensions=bob.buildout buildout:auto-checkout=
script:
# - ./bin/python -c 'import pkg_resources; from bob.bio.base import get_config; print(get_config())'
- ./bin/coverage run --source=gridtk ./bin/nosetests -sv
- ./bin/sphinx-build -b doctest doc sphinx
- ./bin/sphinx-build -b html doc sphinx
after_success:
- coveralls
- wget https://raw.githubusercontent.com/bioidiap/bob.extension/master/scripts/upload-{sphinx,wheel}.sh
- chmod a+x upload-sphinx.sh upload-wheel.sh
- ./upload-sphinx.sh
- ./upload-wheel.sh
