#!/idiap/group/torch5spro/nightlies/externals/v2/linux-x86_64/pyenv/bin/python
# vim: set fileencoding=utf-8 :
# Andre Anjos <andre.anjos@idiap.ch>
# Wed 24 Aug 2011 17:21:28 CEST

import os
import sys
 
install_dir = os.path.realpath(os.path.dirname(sys.argv[0]))
sys.path.append(install_dir)

from gridtk.scripts.grid import main
main()
