{% set name = 'gridtk' %}
{% set project_dir = environ.get('RECIPE_DIR') + '/..' %}

package:
  name: {{ name }}
  version: {{ environ.get('BOB_PACKAGE_VERSION', '0.0.1') }}

build:
  entry_points:
    - jman = gridtk.script.jman:main
    - jgen = gridtk.script.jgen:main
    - grid = gridtk.script.grid:main
    - qstat.py = gridtk.script.grid:main
    - qdel.py = gridtk.script.grid:main
    - qsub.py = gridtk.script.grid:main
    - man.py = gridtk.script.grid:main
  number: {{ environ.get('BOB_BUILD_NUMBER', 0) }}
  run_exports:
    - {{ pin_subpackage(name) }}
  script:
    - cd {{ project_dir }}
    {% if environ.get('BUILD_EGG') %}
    - python setup.py sdist --formats=zip
    {% endif %}
    - python setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python {{ python }}
    - setuptools {{ setuptools }}
    - bob.extension
    - jinja2 {{ jinja2 }}
    - pyyaml {{ pyyaml }}
    - sqlalchemy {{ sqlalchemy }}
  run:
    - python
    - setuptools
    - jinja2 {{ pin_compatible('jinja2') }}
    - pyyaml {{ pin_compatible('pyyaml') }}
    - sqlalchemy {{ pin_compatible('sqlalchemy') }}

test:
  imports:
    - {{ name }}
  commands:
    - jman --help
    - jgen --help
    - nosetests --with-coverage --cover-package={{ name }} -sv {{ name }}
    - sphinx-build -aEW {{ project_dir }}/doc {{ project_dir }}/sphinx
    - sphinx-build -aEb doctest {{ project_dir }}/doc sphinx
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name }}  # [osx]
  requires:
    - nose {{ nose }}
    - coverage {{ coverage }}
    - sphinx {{ sphinx }}
    - sphinx_rtd_theme {{ sphinx_rtd_theme }}

about:
  home: https://www.idiap.ch/software/bob/
  license: GNU General Public License v3 (GPLv3)
  summary: Parallel Job Manager
  license_family: GPL
